### ISSUE TITLE
Add gh-pages branch

### ISSUE THREAD

**Issue by rileyjshaw** [darius/math-toys#2]
GitHub serves static assets if you [create a gh-pages branch](https://pages.github.com/). This will allow folks to try the demos on darius.github.io/math-toys/rulers.html, etc. :)

[Forked example](rileyjshaw.github.io/math-toys/rulers.html)

Wish I could have made this a pull-request, but you need write access to create a new branch ¯_(ツ)_/¯

**Comment by rileyjshaw** [comment]
Also, this covers how to set gh-pages to your default branch if you don't want to have to update two branches: https://pages.github.com/

**Comment by darius** [comment]
Thanks for pointing this out! I didn't know.

I've been syncing to http://wry.me/math-toys/sheet.html and so on, which will do for now, but I'll keep this in mind.

Are you interested in chatting about where I should take this project?

**Comment by rileyjshaw** [comment]
Oh, cool! That works too :)

Very interested! What sort of direction did you have in mind when you picked the project up?

**Comment by rileyjshaw** [comment]
^ (this discussion might deserve it's own thread!)

**Comment by darius** [comment]
Great. :) I just posted a braindump in #3.
